theme: jekyll-theme-cayman

# Site settings
title: Isabelle Zulip
email: kevin.kappelmann@tum.de
description: Archive of the Isabelle Zulip chat at https://isabelle.zulipchat.com.
baseurl: "/archive" # the subpath of your site, e.g. /blog
url: "https://isabelle-prover.github.io/zulip-archive" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  smart_quotes: ["apos", "apos", "quot", "quot"]

exclude: ["*.py"]
