theme: jekyll-theme-cayman

# Site settings
title: Isabelle Zulip
email: kevin.kappelmann@tum.de
description: Archive of the Isabelle Zulip chat at https://isabelle.zulipchat.com.

exclude: ["*.py"]

plugins:
  - jekyll-sitemap
